name = "tuquet-storage"
pages_build_output_dir = "./frontend-dist"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
STORAGE_PREFIX = "tenants"

[[d1_databases]]
binding = "img_d1"
database_name = "tuquet-storage-d1"
database_id = "0d2f4c7a-5544-4b6e-bc8f-102daa01305f"

[[r2_buckets]]
binding = "img_r2"
bucket_name = "tuquet-storage"

[[kv_namespaces]]
binding = "img_url"
id = "31f62562bbd743fb939b0cb70c8d353b"
